[package]
name = "dog"
version = "0.3.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
fitsio-pure = { version = "0.9.4", features = ["compat"] }
polars = {version = "0.46.0", features=["parquet", "csv",  "dtype-i16"]}
rayon = "1.11.0"
